kind: Service
apiVersion: v1
metadata:
  name: timeoff-app-service
spec:
  type: NodePort
  selector:
    app: timeoff-app
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeoff-app-deployment
  labels:
    app: timeoff-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timeoff-app
  template: 
    metadata:
      labels:
        app: timeoff-app
    spec:
      containers:
      - name: timeoff-app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 3000
